#!/usr/bin/env python3

import argparse
import subprocess
import shutil
import sys
import os
import json
from urllib.parse import urlparse
import logging

TAG = "v0.2.0"


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument("--namespace", default="teamkujira")
    parser.add_argument("--debug", action="store_true")

    subparsers = parser.add_subparsers()
    subparsers.required = True
    subparsers.dest = "command"

    init_parser = subparsers.add_parser("init", help="initialize new pond")
    init_parser.add_argument("--nodes", type=int, default=1,
                             help="number of validators")
    init_parser.add_argument("--podman", action="store_true",
                             help="use podman")
    init_parser.add_argument("--docker", action="store_true",
                             help="use docker")
    init_parser.add_argument("--tag", default=TAG, help="tag")

    start_parser = subparsers.add_parser("start", help="start components")
    start_parser.add_argument("target", nargs="?")

    stop_parser = subparsers.add_parser("stop", help="stop components")
    stop_parser.add_argument("target", nargs="?")

    subparsers.add_parser("info", help="info components")
    subparsers.add_parser("tags", help="print available tags")

    return parser.parse_args()


def start_node_cmd(cmd, namespace, name, version, home, ports):
    port_args = " ".join([f"-p 127.0.0.1:{x}:{x}" for x in ports])
    uid = os.getuid()

    commands = {
        "docker": [
            f"docker rm -f {name}".split(),
            f"docker run -e USER={uid} -d {port_args} --network pond --name {name} --network-alias {name} -v {home}/{name}:/kujira {namespace}/kujira:{version} kujirad --home /kujira start".split()
        ],
        "podman": [
            f"podman run --name {name} -d --pod pond -v {home}/{name}:/kujira {namespace}/kujira:{version} kujirad --home /kujira start".split()
        ]
    }

    return commands.get(cmd)


def start_feeder_cmd(cmd, namespace, name, version, home, port):
    uid = os.getuid()

    commands = {
        "docker": [
            f"docker rm {name}".split(),
            f"docker run -e USER={uid} -d -p 127.0.0.1:{port}:{port} --network pond --network-alias {name} --name {name} -v {home}/{name}:/feeder {namespace}/feeder:{version} price-feeder config.toml".split()
        ],
        "podman": [
            f"podman run --name {name} -d --pod pond -v {home}/{name}:/feeder {namespace}/feeder:{version} price-feeder config.toml".split()
        ]
    }

    return commands.get(cmd)


def start_relayer_cmd(cmd, namespace, version, home):
    uid = os.getuid()

    commands = {
        "docker": [
            f"docker rm relayer".split(),
            f"docker run -e USER={uid} -d --network pond --network-alias relayer --name relayer -v {home}/relayer:/relayer {namespace}/relayer:{version} link-and-start-pond.sh".split(),
        ],
        "podman": [
            f"podman run --name relayer -d --pod pond -v {home}/relayer:/relayer {namespace}/relayer:{version} link-and-start-pond.sh".split(),
        ]
    }

    return commands.get(cmd)


def init(home, args):
    cmd = None
    extra_args = []

    if args.docker:
        cmd = "docker"
    elif args.podman:
        cmd = "podman"
    else:
        if shutil.which("docker"):
            cmd = "docker"
        elif shutil.which("podman"):
            cmd = "podman"

    if not cmd:
        error("neither docker nor podman found")

    if cmd == "docker":
        uid = os.getuid()
        cmd = ["docker", "run", "-e", f"USER={uid}"]
    else:
        cmd = ["podman", "run"]
        extra_args = ["--podman"]

    if not os.path.isdir(home):
        os.mkdir(home)
    else:
        if os.listdir(home):
            while True:
                sys.stdout.write(
                    "Delete existing chain data and init new chain? [y/N] "
                )
                choice = input().lower()

                if choice in ["y", "yes"]:
                    break

                if choice in ["", "n", "no"]:
                    return

    cmd += [
        "-v", f"{home}:/tmp/pond",
        f"docker.io/{args.namespace}/prepare:{args.tag}",
        "prepare.py", "--nodes", f"{args.nodes}", "--clear"
    ] + extra_args

    subprocess.run(cmd)


def info(home):
    print(json.dumps(
        json.load(open(f"{home}/pond.json", "r")),
        indent=2,
    ))


def start(args, config, home):
    cmd = config.get("command")
    if not cmd:
        error("command not set")

    ns = args.namespace

    commands = [["sleep", "2"]]

    ports = []
    for chain_id, validators in config["validators"].items():
        for validator in validators:
            node_ports = [
                urlparse(validator["api_url"]).port,
                validator["rpc_url"].split(":")[-1],
                validator["rpc_url"].split(":")[-1][:-2] + "90"
            ]

            # backwards compatibility
            if "app_url" in validator.keys():
                node_ports.append(urlparse(validator["app_url"]).port)

            ports += node_ports

            name = validator["moniker"].lower()
            version = config["version"]["kujira"]
            commands = start_node_cmd(
                cmd, ns, name, version, home, node_ports
            ) + commands

            if chain_id == "pond-1":
                name = name.replace("kujira", "feeder")
                version = config["version"]["feeder"]
                node_port = urlparse(validator["feeder_url"]).port
                ports.append(node_port)
                commands += start_feeder_cmd(
                    cmd, ns, name, version, home, node_port
                )

    version = config["version"]["relayer"]
    commands += start_relayer_cmd(cmd, ns, version, home)

    port_args = " ".join([f"-p {x}:{x}" for x in ports])

    if cmd == "podman":
        commands = [
            f"podman pod rm --force pond".split(),
            f"podman pod create --name pond {port_args}".split()
        ] + commands

    if cmd == "docker":
        commands = [
            "docker network rm pond".split(),
            "docker network create pond".split()
        ] + commands

    if not config.get("codes"):
        commands.append(["sleep", "5"])

        extra = []
        if cmd == "docker":
            uid = os.getuid()
            command = ["docker", "run", "-e",
                       f"USER={uid}", "--network", "pond"]
            host = "kujira1-1"
        else:
            command = ["podman", "run", "--pod", "pond"]
            host = "127.0.0.1"

        version = config["version"]["prepare"]

        command += [
            "-v", f"{home}:/tmp/pond",
            f"docker.io/{args.namespace}/prepare:{version}",
            "/tmp/contracts/deploy.py", "/tmp/contracts/plans",
            "--home", "/tmp/pond/kujira1-1",
            "--node", f"http://{host}:10157",
            "--pond-json", "/tmp/pond/pond.json"
        ]

        commands.append(command)

    run(commands)


def stop(config):
    cmd = config.get("command")
    if not cmd:
        error("command not set")

    commands = [
        [cmd, "kill", "relayer"]
    ]

    for chain_id, validators in config["validators"].items():
        for validator in validators:
            name = validator["moniker"].lower()
            commands.append([cmd, "kill", name])

            if chain_id == "pond-1":
                name = name.replace("kujira", "feeder")
                commands.append([cmd, "kill", name])

    if cmd == "podman":
        commands.append([cmd, "pod", "kill", "pond"])

    run(commands)


def run(commands):
    for cmd in commands:
        debug(" ".join(cmd))
        # subprocess.call(cmd)
        subprocess.call(cmd, stdout=subprocess.DEVNULL)


def main():
    args = parse_args()

    log_level = logging.INFO
    if args.debug:
        log_level = logging.DEBUG

    logging.basicConfig(
        level=log_level,
        format="%(levelname)s %(message)s"
    )

    logging.addLevelName(logging.DEBUG, "DBG")
    logging.addLevelName(logging.INFO, "INF")
    logging.addLevelName(logging.WARNING, "WRN")
    logging.addLevelName(logging.ERROR, "ERR")

    home = os.path.expanduser("~") + "/.pond"
    config = None

    if args.command == "init":
        init(home, args)
    else:
        if not os.path.isdir(home):
            error(f"{home} not found, you need to init pond at first")

        config = json.load(open(f"{home}/pond.json", "r"))

        if args.command == "start":
            if is_running(config):
                info("pond already running")
                return

            start(args, config, home)
        elif args.command == "stop":
            if not is_running(config):
                return
            stop(config)
        elif args.command == "info":
            info(home)
        elif args.command == "tags":
            for i in TAGS:
                print(i)


def is_running(config):
    cmd = config.get("command")
    if not cmd:
        error("command not set")

    command = [
        cmd, "ps", "--format", "json"
    ]

    result = subprocess.check_output(command)
    if not result:
        return False

    result = result.decode('utf8').replace("'", '"')

    if cmd == "docker":
        result = result.replace("\n", ",")
        result = f"[{result[:-1]}]"
    else:
        result = result[:-1]

    data = json.loads(result)

    for i in data:
        if cmd == "docker":
            if i.get("Networks") == "pond":
                return True
        else:
            if i.get("PodName") == "pond":
                return True

    return False


def error(message=None, **kwargs):
    log(message, logging.ERROR, kwargs)
    sys.exit(1)


def warning(message=None, **kwargs):
    log(message, logging.WARNING, kwargs)


def debug(message=None, **kwargs):
    log(message, logging.DEBUG, kwargs)


def info(message=None, **kwargs):
    log(message, logging.INFO, kwargs)


def log(message, level, kwargs):
    tags = []
    for k, v in kwargs.items():
        tags.append(f"{k}={v}")

    tags = ", ".join(tags)

    if message:
        message = f"{message} {tags}"
    else:
        message = tags

    logging.log(level, message)


if __name__ == "__main__":
    main()
