history_db = "/home/feeder/feeder.db"

[server]
listen_addr = "0.0.0.0:{{ .Port }}"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "USDT"
threshold = "2"

[[currency_pairs]]
base = "BTC"
quote = "USDT"
providers = ["binance", "bitget", "lbank", "mexc", "okx", "xt"]

[[currency_pairs]]
base = "ETH"
quote = "USDT"
providers = ["binance", "bitget", "lbank", "mexc", "okx", "xt"]

[[currency_pairs]]
base = "STETH"
quote = "USDT"
providers = ["bybit", "okx", "bitget", "gate"]

[[currency_pairs]]
base = "USDT"
quote = "USD"
providers = ["binanceus", "crypto", "gate", "kraken"]

[[currency_pairs]]
base = "USK"
quote = "USDC"
providers = ["finv2"]

[[currency_pairs]]
base = "KUJI"
quote = "USDC"
providers = ["finv2"]

[[currency_pairs]]
base = "USDC"
quote = "USDT"
providers = ["binance", "bybit", "huobi", "kucoin", "lbank"]

[[currency_pairs]]
base = "SOL"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "PEPE"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "NOT"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "WIF"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "XRP"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "BNB"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "BONK"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "DOGE"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "AVAX"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "BOME"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "PEOPLE"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "FLOKI"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ETHFI"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "SHIB"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "TIA"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "NEAR"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ARB"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "RUNE"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "LINK"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "WLD"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ADA"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "TRX"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ORDI"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "FET"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "RNDR"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "MATIC"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "DOT"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "PENDLE"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "TAO"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ENA"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "SEI"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "LISTA"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "BOND"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ZEN"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "FIL"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "SAGA"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "DYM"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "JUP"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "CRV"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "LTC"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "XAI"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "SUI"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "LDO"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "INJ"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "STRK"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "MKR"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "FTM"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ICP"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "EGLD"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "JTO"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "REZ"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "APT"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "UNI"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "YGG"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "PIXEL"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ETC"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "AEVO"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "MANTA"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "BETA"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ATOM"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "PYTH"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ARKM"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "EOS"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "CHR"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "DYDX"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "BAKE"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "CFX"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "SSV"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "VET"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ELF"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ASTR"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "ALT"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "TNSR"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "MDX"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "EDU"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "STX"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "AXL"
quote = "USDT"
providers = ["binance"]

[[currency_pairs]]
base = "HBAR"
quote = "USDT"
providers = ["binance"]

[[provider_min_overrides]]
denoms = [
    "ADA",
    "ARB",
    "AVAX",
    "BNB",
    "BOME",
    "BOND",
    "BONK",
    "BTC",
    "CRV",
    "DOGE",
    "DOT",
    "DYM",
    "ENA",
    "ETH",
    "ETHFI",
    "FET",
    "FIL",
    "FLOKI",
    "INJ",
    "JUP",
    "KUJI",
    "LDO",
    "LINK",
    "LISTA",
    "LTC",
    "MATIC",
    "MKR",
    "NEAR",
    "NOT",
    "ORDI",
    "PENDLE",
    "PEOPLE",
    "PEPE",
    "RNDR",
    "RUNE",
    "SAGA",
    "SEI",
    "SHIB",
    "SOL",
    "STETH",
    "STRK",
    "SUI",
    "TAO",
    "TIA",
    "TRX",
    "USDC",
    "USDT",
    "USDT",
    "USK",
    "WIF",
    "WLD",
    "XAI",
    "XRP",
    "ZEN",
    "FTM",
    "ICP",
    "EGLD",
    "JTO",
    "REZ",
    "APT",
    "UNI",
    "YGG",
    "PIXEL",
    "ETC",
    "AEVO",
    "MANTA",
    "BETA",
    "ATOM",
    "PYTH",
    "ARKM",
    "EOS",
    "CHR",
    "DYDX",
    "BAKE",
    "CFX",
    "SSV",
    "VET",
    "ELF",
    "ASTR",
    "ALT",
    "TNSR",
    "MDX",
    "EDU",
    "STX",
    "AXL",
    "HBAR",
]
providers = 1

[[provider_endpoints]]
name = "finv2"
urls = [
    "https://kujira.api.kjnodes.com",
    "https://kujira-api.lavenderfive.com",
    "https://kujira-rest.publicnode.com",
    "https://rest-kujira.ecostake.com",
    "https://kujira-api.ibs.team",
    "https://lcd-kujira.whispernode.com",
    "https://api-kujira.mms.team",
    "https://api-kujira.starsquid.io",
]

[contract_addresses.finv2]
USDCUSK = "kujira15a657mgszm30vdhytpmfslcyc4cztn5lsuv9rxzwdqmuwgd8znps8l3yy2"
KUJIUSDC = "kujira1pw96huy6z02uk8hdpruk6g8u700dp8yxjhp46c24rwkzay2lfd3quqdum5"
